#type: args

train:
  epochs: 100       ## Pre-raining epochs using IIF masking default:500
  batch_size: 8   ## Batch size default: 8
  lr: 1.0e-3

diffusion:
  layers: 4         ##  Number of residual layers in the denoising block
  channels: 64      ##  Number of channels for projections in the denoising block (residual channels) default: 64
  diffusion_embedding_dim: 128    ## Diffusion step embedding dimension default: 128
  beta_start: 0.0001      ## minimum noise level in the forward pass
  beta_end: 0.5           ## maximum noise level in the forward pass
  num_steps: 50           ## Total number of diffusion steps default = 50
  schedule: "quad"        ## Type of noise scheduler

model:
  timeemb: 128            ## Time embedding dimension default: 128
  featureemb: 16          ## Feature embedding dimension default: 16
  mix_masking_strategy: "equal_p"   ## Mix masking strategy
  time_strategy: "hawkes"           ## Time embedding type
  
embedding:
  timeemb: 128           ## Time embedding dimension default: 128
  featureemb: 16          ## Feature embedding dimension default: 16
  num_feat: 19            ## Total number of features in the MTS (K)
  num_timestamps: 66      ## Total number of timestamps in the MTS (L)
  classes: 1
  channels: 16            ## Number of embedding dimension in both temporal and spatial encoders default: 16
  nheads: 8               ## Number of heads in the temporal and spatial encoders default: 8
  
finetuning:
  epochs: 50            ## Number of finetuning epochs for the downstream task default: 20
  # 